//------------------------------------------------------------------------------
// <auto-generated>
// This code is generated by the tool.
// Runtime version: 4.0.30319.34003
//
// Changes to this file may cause incorrect behavior, and if
// Regenerate the code, these changes will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUGENCharsSet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
